version: '3.8'

services:
  payments: # PHP 7.3 app
    build: apps/payments
    ports:
      - "8001:80"
    volumes:
      # bind-mount used to mount src code into image for development.
      - ./apps/payments/src:/srv/myapp
      - ./shared/important-config:/srv/config/important-config

  civicrm: # PHP 7.4 app
    build: apps/civicrm
    ports:
      - "8002:80"
    volumes:
      # bind-mount used to mount src code into image for development.
      - ./apps/civicrm/src:/srv/myapp
      - ./shared/important-config:/srv/config/important-config


  php8: # PHP 8 app
    build: apps/php-8-is-here
    ports:
      - "8003:80"
    volumes:
      # bind-mount used to mount src code into image for development.
      - ./apps/php-8-is-here/src:/srv/myapp
      - ./shared/important-config:/srv/config/important-config

  fundrasing-tools: # Python3 app
    build: apps/fundraising-tools
    ports:
      - "8004:80"
    volumes:
      # bind-mount used to mount src code into image for development.
      - ./apps/fundraising-tools/src:/srv/myapp
      - ./shared/important-config:/srv/config/important-config

  process-control: #Python3 app
    build: apps/process-control
    volumes:
      # bind-mount used to mount src code into image for development.
      - ./apps/process-control:/srv/process-control
      - ./shared/important-config:/srv/config/important-config